Fixed a bug where the gallery title is always "None"
happypandax/plugins pull request #39
Opened 2020-08-31 14:04 UTC by AnonRaver

Title was always "None" because the page layout changed and they put multiple <span> inside the <h1>

2020-08-31 21:19 UTC, twiddli commented
Hello thank you for the contribution! Can you bump the version in the `hplugin.json` file and add the change to the readme at the bottom?

2020-08-31 21:21 UTC, twiddli requested changes
Hello thank you for the contribution! Can you bump the version in the `hplugin.json` file and add a description of the change to the readme at the bottom?

2020-12-22 01:00 UTC, moisi123 commented
Hello, thanks for the bug fix.
Is it possible change the folder where the comic is downloaded by its code instead of the comic name?
![image](https://user-images.githubusercontent.com/76458321/102836038-97a42700-43f8-11eb-98eb-358d9b41641a.png)
![image](https://user-images.githubusercontent.com/76458321/102836061-a985ca00-43f8-11eb-8527-628708d05fc1.png)
I tried to do it myself changing the html that beautifulsoup searchs but it cant do it works :~
Regards.

2021-01-02 00:52 UTC, Rooba approved these changes

2021-03-21 14:27 UTC, merged